// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtz5cZ--aUrAM6KbSev_KxhdsjVD9jXKY',
    appId: '1:294254128920:web:3b2e8a397f14ed04a1786d',
    messagingSenderId: '294254128920',
    projectId: 'hydr8-wellness-tracker',
    authDomain: 'hydr8-wellness-tracker.firebaseapp.com',
    storageBucket: 'hydr8-wellness-tracker.firebasestorage.app',
    measurementId: 'G-Q2Q433FCQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu57p4p4ExOuvHyA_CG4dM9b9eTT9ogJQ',
    appId: '1:294254128920:android:29f98f8dd085e49ea1786d',
    messagingSenderId: '294254128920',
    projectId: 'hydr8-wellness-tracker',
    storageBucket: 'hydr8-wellness-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8qBWKk1JhWeeRpUyM2m6th2If3dmbmyo',
    appId: '1:294254128920:ios:3796cd6f0077d7efa1786d',
    messagingSenderId: '294254128920',
    projectId: 'hydr8-wellness-tracker',
    storageBucket: 'hydr8-wellness-tracker.firebasestorage.app',
    iosBundleId: 'com.example.hydrateTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8qBWKk1JhWeeRpUyM2m6th2If3dmbmyo',
    appId: '1:294254128920:ios:3796cd6f0077d7efa1786d',
    messagingSenderId: '294254128920',
    projectId: 'hydr8-wellness-tracker',
    storageBucket: 'hydr8-wellness-tracker.firebasestorage.app',
    iosBundleId: 'com.example.hydrateTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtz5cZ--aUrAM6KbSev_KxhdsjVD9jXKY',
    appId: '1:294254128920:web:8ad1cd97b6518671a1786d',
    messagingSenderId: '294254128920',
    projectId: 'hydr8-wellness-tracker',
    authDomain: 'hydr8-wellness-tracker.firebaseapp.com',
    storageBucket: 'hydr8-wellness-tracker.firebasestorage.app',
    measurementId: 'G-L4HW7KZ1PV',
  );
}
